/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables.records;


import jooq.public_.tables.Discounts;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiscountsRecord extends TableRecordImpl<DiscountsRecord> implements Record9<String, BigDecimal, BigDecimal, Boolean, Boolean, Boolean, Boolean, Boolean, String> {

    private static final long serialVersionUID = 299484266;

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.PRODUCT</code>.
     */
    public void setProduct(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.PRODUCT</code>.
     */
    public String getProduct() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.OLD_PRICE</code>.
     */
    public void setOldPrice(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.OLD_PRICE</code>.
     */
    public BigDecimal getOldPrice() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.DISCOUNT_PRICE</code>.
     */
    public void setDiscountPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.DISCOUNT_PRICE</code>.
     */
    public BigDecimal getDiscountPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.MONDAY</code>.
     */
    public void setMonday(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.MONDAY</code>.
     */
    public Boolean getMonday() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.TUESDAY</code>.
     */
    public void setTuesday(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.TUESDAY</code>.
     */
    public Boolean getTuesday() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.WEDNESDAY</code>.
     */
    public void setWednesday(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.WEDNESDAY</code>.
     */
    public Boolean getWednesday() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.THURSDAY</code>.
     */
    public void setThursday(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.THURSDAY</code>.
     */
    public Boolean getThursday() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.FRIDAY</code>.
     */
    public void setFriday(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.FRIDAY</code>.
     */
    public Boolean getFriday() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>PUBLIC.DISCOUNTS.REPEAT</code>.
     */
    public void setRepeat(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.DISCOUNTS.REPEAT</code>.
     */
    public String getRepeat() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, BigDecimal, BigDecimal, Boolean, Boolean, Boolean, Boolean, Boolean, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<String, BigDecimal, BigDecimal, Boolean, Boolean, Boolean, Boolean, Boolean, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Discounts.DISCOUNTS.PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return Discounts.DISCOUNTS.OLD_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Discounts.DISCOUNTS.DISCOUNT_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Discounts.DISCOUNTS.MONDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Discounts.DISCOUNTS.TUESDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Discounts.DISCOUNTS.WEDNESDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Discounts.DISCOUNTS.THURSDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Discounts.DISCOUNTS.FRIDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Discounts.DISCOUNTS.REPEAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getOldPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getMonday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getTuesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getWednesday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getThursday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getFriday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRepeat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value1(String value) {
        setProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value2(BigDecimal value) {
        setOldPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value3(BigDecimal value) {
        setDiscountPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value4(Boolean value) {
        setMonday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value5(Boolean value) {
        setTuesday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value6(Boolean value) {
        setWednesday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value7(Boolean value) {
        setThursday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value8(Boolean value) {
        setFriday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord value9(String value) {
        setRepeat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DiscountsRecord values(String value1, BigDecimal value2, BigDecimal value3, Boolean value4, Boolean value5, Boolean value6, Boolean value7, Boolean value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiscountsRecord
     */
    public DiscountsRecord() {
        super(Discounts.DISCOUNTS);
    }

    /**
     * Create a detached, initialised DiscountsRecord
     */
    public DiscountsRecord(String product, BigDecimal oldPrice, BigDecimal discountPrice, Boolean monday, Boolean tuesday, Boolean wednesday, Boolean thursday, Boolean friday, String repeat) {
        super(Discounts.DISCOUNTS);

        set(0, product);
        set(1, oldPrice);
        set(2, discountPrice);
        set(3, monday);
        set(4, tuesday);
        set(5, wednesday);
        set(6, thursday);
        set(7, friday);
        set(8, repeat);
    }
}
