/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables.records;


import jooq.public_.tables.Employees;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends TableRecordImpl<EmployeesRecord> implements Record6<String, String, String, String, BigDecimal, Date> {

    private static final long serialVersionUID = 1139614282;

    /**
     * Setter for <code>PUBLIC.EMPLOYEES.IMAGE_PATH</code>.
     */
    public void setImagePath(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEES.IMAGE_PATH</code>.
     */
    public String getImagePath() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEES.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEES.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEES.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEES.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEES.POSITION</code>.
     */
    public void setPosition(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEES.POSITION</code>.
     */
    public String getPosition() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEES.WAGE</code>.
     */
    public void setWage(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEES.WAGE</code>.
     */
    public BigDecimal getWage() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEES.HIRED_DATE</code>.
     */
    public void setHiredDate(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEES.HIRED_DATE</code>.
     */
    public Date getHiredDate() {
        return (Date) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, BigDecimal, Date> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, BigDecimal, Date> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Employees.EMPLOYEES.IMAGE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Employees.EMPLOYEES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Employees.EMPLOYEES.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Employees.EMPLOYEES.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Employees.EMPLOYEES.WAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return Employees.EMPLOYEES.HIRED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getImagePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getWage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getHiredDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value1(String value) {
        setImagePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value4(String value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value5(BigDecimal value) {
        setWage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord value6(Date value) {
        setHiredDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmployeesRecord values(String value1, String value2, String value3, String value4, BigDecimal value5, Date value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(String imagePath, String name, String email, String position, BigDecimal wage, Date hiredDate) {
        super(Employees.EMPLOYEES);

        set(0, imagePath);
        set(1, name);
        set(2, email);
        set(3, position);
        set(4, wage);
        set(5, hiredDate);
    }
}
