/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables.records;


import jooq.public_.tables.Schedule;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScheduleRecord extends TableRecordImpl<ScheduleRecord> implements Record11<String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -1031480638;

    /**
     * Setter for <code>PUBLIC.SCHEDULE.DAY</code>.
     */
    public void setDay(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.DAY</code>.
     */
    public String getDay() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.B1_E1</code>.
     */
    public void setB1E1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.B1_E1</code>.
     */
    public String getB1E1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.B1_E2</code>.
     */
    public void setB1E2(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.B1_E2</code>.
     */
    public String getB1E2() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.LU_E1</code>.
     */
    public void setLuE1(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.LU_E1</code>.
     */
    public String getLuE1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.LU_E2</code>.
     */
    public void setLuE2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.LU_E2</code>.
     */
    public String getLuE2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.B2_E1</code>.
     */
    public void setB2E1(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.B2_E1</code>.
     */
    public String getB2E1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.B2_E2</code>.
     */
    public void setB2E2(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.B2_E2</code>.
     */
    public String getB2E2() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.ST_E1</code>.
     */
    public void setStE1(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.ST_E1</code>.
     */
    public String getStE1() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.ST_E2</code>.
     */
    public void setStE2(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.ST_E2</code>.
     */
    public String getStE2() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.AD_E1</code>.
     */
    public void setAdE1(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.AD_E1</code>.
     */
    public String getAdE1() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.SCHEDULE.AD_E2</code>.
     */
    public void setAdE2(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.SCHEDULE.AD_E2</code>.
     */
    public String getAdE2() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Schedule.SCHEDULE.DAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Schedule.SCHEDULE.B1_E1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Schedule.SCHEDULE.B1_E2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Schedule.SCHEDULE.LU_E1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Schedule.SCHEDULE.LU_E2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Schedule.SCHEDULE.B2_E1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Schedule.SCHEDULE.B2_E2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Schedule.SCHEDULE.ST_E1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Schedule.SCHEDULE.ST_E2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Schedule.SCHEDULE.AD_E1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Schedule.SCHEDULE.AD_E2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getDay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getB1E1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getB1E2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLuE1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLuE2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getB2E1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getB2E2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStE1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getStE2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAdE1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAdE2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value1(String value) {
        setDay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value2(String value) {
        setB1E1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value3(String value) {
        setB1E2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value4(String value) {
        setLuE1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value5(String value) {
        setLuE2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value6(String value) {
        setB2E1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value7(String value) {
        setB2E2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value8(String value) {
        setStE1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value9(String value) {
        setStE2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value10(String value) {
        setAdE1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord value11(String value) {
        setAdE2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScheduleRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScheduleRecord
     */
    public ScheduleRecord() {
        super(Schedule.SCHEDULE);
    }

    /**
     * Create a detached, initialised ScheduleRecord
     */
    public ScheduleRecord(String day, String b1E1, String b1E2, String luE1, String luE2, String b2E1, String b2E2, String stE1, String stE2, String adE1, String adE2) {
        super(Schedule.SCHEDULE);

        set(0, day);
        set(1, b1E1);
        set(2, b1E2);
        set(3, luE1);
        set(4, luE2);
        set(5, b2E1);
        set(6, b2E2);
        set(7, stE1);
        set(8, stE2);
        set(9, adE1);
        set(10, adE2);
    }
}
