/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables.records;


import jooq.public_.tables.YearStats;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YearStatsRecord extends TableRecordImpl<YearStatsRecord> implements Record16<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1744443621;

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.YEAR</code>.
     */
    public void setYear(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.YEAR</code>.
     */
    public Integer getYear() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.FOOD_SOLD</code>.
     */
    public void setFoodSold(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.FOOD_SOLD</code>.
     */
    public Integer getFoodSold() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.BAKERY_SOLD</code>.
     */
    public void setBakerySold(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.BAKERY_SOLD</code>.
     */
    public Integer getBakerySold() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.CANDY_SOLD</code>.
     */
    public void setCandySold(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.CANDY_SOLD</code>.
     */
    public Integer getCandySold() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.CHIPS_SOLD</code>.
     */
    public void setChipsSold(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.CHIPS_SOLD</code>.
     */
    public Integer getChipsSold() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.DRINKS_SOLD</code>.
     */
    public void setDrinksSold(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.DRINKS_SOLD</code>.
     */
    public Integer getDrinksSold() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.SODAS_SOLD</code>.
     */
    public void setSodasSold(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.SODAS_SOLD</code>.
     */
    public Integer getSodasSold() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.WATERS_SOLD</code>.
     */
    public void setWatersSold(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.WATERS_SOLD</code>.
     */
    public Integer getWatersSold() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.JUICES_SOLD</code>.
     */
    public void setJuicesSold(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.JUICES_SOLD</code>.
     */
    public Integer getJuicesSold() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.COFFEES_SOLD</code>.
     */
    public void setCoffeesSold(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.COFFEES_SOLD</code>.
     */
    public Integer getCoffeesSold() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.FROZEN_SOLD</code>.
     */
    public void setFrozenSold(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.FROZEN_SOLD</code>.
     */
    public Integer getFrozenSold() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.MISC_SOLD</code>.
     */
    public void setMiscSold(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.MISC_SOLD</code>.
     */
    public Integer getMiscSold() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.TOTAL_SALES</code>.
     */
    public void setTotalSales(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.TOTAL_SALES</code>.
     */
    public Integer getTotalSales() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.TOTAL_ITEMS_SOLD</code>.
     */
    public void setTotalItemsSold(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.TOTAL_ITEMS_SOLD</code>.
     */
    public Integer getTotalItemsSold() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.TOTAL_INCOME</code>.
     */
    public void setTotalIncome(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.TOTAL_INCOME</code>.
     */
    public BigDecimal getTotalIncome() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>PUBLIC.YEAR_STATS.TOTAL_PROFIT</code>.
     */
    public void setTotalProfit(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>PUBLIC.YEAR_STATS.TOTAL_PROFIT</code>.
     */
    public BigDecimal getTotalProfit() {
        return (BigDecimal) get(15);
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, BigDecimal, BigDecimal> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return YearStats.YEAR_STATS.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return YearStats.YEAR_STATS.FOOD_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return YearStats.YEAR_STATS.BAKERY_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return YearStats.YEAR_STATS.CANDY_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return YearStats.YEAR_STATS.CHIPS_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return YearStats.YEAR_STATS.DRINKS_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return YearStats.YEAR_STATS.SODAS_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return YearStats.YEAR_STATS.WATERS_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return YearStats.YEAR_STATS.JUICES_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return YearStats.YEAR_STATS.COFFEES_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return YearStats.YEAR_STATS.FROZEN_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return YearStats.YEAR_STATS.MISC_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return YearStats.YEAR_STATS.TOTAL_SALES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return YearStats.YEAR_STATS.TOTAL_ITEMS_SOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return YearStats.YEAR_STATS.TOTAL_INCOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field16() {
        return YearStats.YEAR_STATS.TOTAL_PROFIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFoodSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getBakerySold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCandySold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getChipsSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDrinksSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSodasSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getWatersSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getJuicesSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getCoffeesSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getFrozenSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getMiscSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getTotalSales();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getTotalItemsSold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getTotalIncome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value16() {
        return getTotalProfit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value1(Integer value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value2(Integer value) {
        setFoodSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value3(Integer value) {
        setBakerySold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value4(Integer value) {
        setCandySold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value5(Integer value) {
        setChipsSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value6(Integer value) {
        setDrinksSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value7(Integer value) {
        setSodasSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value8(Integer value) {
        setWatersSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value9(Integer value) {
        setJuicesSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value10(Integer value) {
        setCoffeesSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value11(Integer value) {
        setFrozenSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value12(Integer value) {
        setMiscSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value13(Integer value) {
        setTotalSales(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value14(Integer value) {
        setTotalItemsSold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value15(BigDecimal value) {
        setTotalIncome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord value16(BigDecimal value) {
        setTotalProfit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStatsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, Integer value12, Integer value13, Integer value14, BigDecimal value15, BigDecimal value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached YearStatsRecord
     */
    public YearStatsRecord() {
        super(YearStats.YEAR_STATS);
    }

    /**
     * Create a detached, initialised YearStatsRecord
     */
    public YearStatsRecord(Integer year, Integer foodSold, Integer bakerySold, Integer candySold, Integer chipsSold, Integer drinksSold, Integer sodasSold, Integer watersSold, Integer juicesSold, Integer coffeesSold, Integer frozenSold, Integer miscSold, Integer totalSales, Integer totalItemsSold, BigDecimal totalIncome, BigDecimal totalProfit) {
        super(YearStats.YEAR_STATS);

        set(0, year);
        set(1, foodSold);
        set(2, bakerySold);
        set(3, candySold);
        set(4, chipsSold);
        set(5, drinksSold);
        set(6, sodasSold);
        set(7, watersSold);
        set(8, juicesSold);
        set(9, coffeesSold);
        set(10, frozenSold);
        set(11, miscSold);
        set(12, totalSales);
        set(13, totalItemsSold);
        set(14, totalIncome);
        set(15, totalProfit);
    }
}
