/**
 * This class is generated by jOOQ
 */
package jooq.information_schema;


import jooq.DefaultCatalog;
import jooq.information_schema.tables.Catalogs;
import jooq.information_schema.tables.Collations;
import jooq.information_schema.tables.ColumnPrivileges;
import jooq.information_schema.tables.Columns;
import jooq.information_schema.tables.Constants;
import jooq.information_schema.tables.Constraints;
import jooq.information_schema.tables.CrossReferences;
import jooq.information_schema.tables.Domains;
import jooq.information_schema.tables.FunctionAliases;
import jooq.information_schema.tables.FunctionColumns;
import jooq.information_schema.tables.Help;
import jooq.information_schema.tables.InDoubt;
import jooq.information_schema.tables.Indexes;
import jooq.information_schema.tables.Locks;
import jooq.information_schema.tables.QueryStatistics;
import jooq.information_schema.tables.Rights;
import jooq.information_schema.tables.Roles;
import jooq.information_schema.tables.Schemata;
import jooq.information_schema.tables.Sequences;
import jooq.information_schema.tables.SessionState;
import jooq.information_schema.tables.Sessions;
import jooq.information_schema.tables.Settings;
import jooq.information_schema.tables.TablePrivileges;
import jooq.information_schema.tables.TableTypes;
import jooq.information_schema.tables.Tables;
import jooq.information_schema.tables.Triggers;
import jooq.information_schema.tables.TypeInfo;
import jooq.information_schema.tables.Users;
import jooq.information_schema.tables.Views;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformationSchema extends SchemaImpl {

    private static final long serialVersionUID = 1394886479;

    /**
     * The reference instance of <code>INFORMATION_SCHEMA</code>
     */
    public static final InformationSchema INFORMATION_SCHEMA = new InformationSchema();

    /**
     * The table <code>INFORMATION_SCHEMA.QUERY_STATISTICS</code>.
     */
    public final QueryStatistics QUERY_STATISTICS = jooq.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

    /**
     * The table <code>INFORMATION_SCHEMA.SESSION_STATE</code>.
     */
    public final SessionState SESSION_STATE = jooq.information_schema.tables.SessionState.SESSION_STATE;

    /**
     * The table <code>INFORMATION_SCHEMA.LOCKS</code>.
     */
    public final Locks LOCKS = jooq.information_schema.tables.Locks.LOCKS;

    /**
     * The table <code>INFORMATION_SCHEMA.SESSIONS</code>.
     */
    public final Sessions SESSIONS = jooq.information_schema.tables.Sessions.SESSIONS;

    /**
     * The table <code>INFORMATION_SCHEMA.TRIGGERS</code>.
     */
    public final Triggers TRIGGERS = jooq.information_schema.tables.Triggers.TRIGGERS;

    /**
     * The table <code>INFORMATION_SCHEMA.DOMAINS</code>.
     */
    public final Domains DOMAINS = jooq.information_schema.tables.Domains.DOMAINS;

    /**
     * The table <code>INFORMATION_SCHEMA.CONSTANTS</code>.
     */
    public final Constants CONSTANTS = jooq.information_schema.tables.Constants.CONSTANTS;

    /**
     * The table <code>INFORMATION_SCHEMA.FUNCTION_COLUMNS</code>.
     */
    public final FunctionColumns FUNCTION_COLUMNS = jooq.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

    /**
     * The table <code>INFORMATION_SCHEMA.CONSTRAINTS</code>.
     */
    public final Constraints CONSTRAINTS = jooq.information_schema.tables.Constraints.CONSTRAINTS;

    /**
     * The table <code>INFORMATION_SCHEMA.CROSS_REFERENCES</code>.
     */
    public final CrossReferences CROSS_REFERENCES = jooq.information_schema.tables.CrossReferences.CROSS_REFERENCES;

    /**
     * The table <code>INFORMATION_SCHEMA.IN_DOUBT</code>.
     */
    public final InDoubt IN_DOUBT = jooq.information_schema.tables.InDoubt.IN_DOUBT;

    /**
     * The table <code>INFORMATION_SCHEMA.VIEWS</code>.
     */
    public final Views VIEWS = jooq.information_schema.tables.Views.VIEWS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLLATIONS</code>.
     */
    public final Collations COLLATIONS = jooq.information_schema.tables.Collations.COLLATIONS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLUMN_PRIVILEGES</code>.
     */
    public final ColumnPrivileges COLUMN_PRIVILEGES = jooq.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLE_PRIVILEGES</code>.
     */
    public final TablePrivileges TABLE_PRIVILEGES = jooq.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

    /**
     * The table <code>INFORMATION_SCHEMA.SCHEMATA</code>.
     */
    public final Schemata SCHEMATA = jooq.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>INFORMATION_SCHEMA.FUNCTION_ALIASES</code>.
     */
    public final FunctionAliases FUNCTION_ALIASES = jooq.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

    /**
     * The table <code>INFORMATION_SCHEMA.RIGHTS</code>.
     */
    public final Rights RIGHTS = jooq.information_schema.tables.Rights.RIGHTS;

    /**
     * The table <code>INFORMATION_SCHEMA.ROLES</code>.
     */
    public final Roles ROLES = jooq.information_schema.tables.Roles.ROLES;

    /**
     * The table <code>INFORMATION_SCHEMA.USERS</code>.
     */
    public final Users USERS = jooq.information_schema.tables.Users.USERS;

    /**
     * The table <code>INFORMATION_SCHEMA.SEQUENCES</code>.
     */
    public final Sequences SEQUENCES = jooq.information_schema.tables.Sequences.SEQUENCES;

    /**
     * The table <code>INFORMATION_SCHEMA.HELP</code>.
     */
    public final Help HELP = jooq.information_schema.tables.Help.HELP;

    /**
     * The table <code>INFORMATION_SCHEMA.SETTINGS</code>.
     */
    public final Settings SETTINGS = jooq.information_schema.tables.Settings.SETTINGS;

    /**
     * The table <code>INFORMATION_SCHEMA.CATALOGS</code>.
     */
    public final Catalogs CATALOGS = jooq.information_schema.tables.Catalogs.CATALOGS;

    /**
     * The table <code>INFORMATION_SCHEMA.TYPE_INFO</code>.
     */
    public final TypeInfo TYPE_INFO = jooq.information_schema.tables.TypeInfo.TYPE_INFO;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLE_TYPES</code>.
     */
    public final TableTypes TABLE_TYPES = jooq.information_schema.tables.TableTypes.TABLE_TYPES;

    /**
     * The table <code>INFORMATION_SCHEMA.INDEXES</code>.
     */
    public final Indexes INDEXES = jooq.information_schema.tables.Indexes.INDEXES;

    /**
     * The table <code>INFORMATION_SCHEMA.COLUMNS</code>.
     */
    public final Columns COLUMNS = jooq.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLES</code>.
     */
    public final Tables TABLES = jooq.information_schema.tables.Tables.TABLES;

    /**
     * No further instances allowed
     */
    private InformationSchema() {
        super("INFORMATION_SCHEMA", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            QueryStatistics.QUERY_STATISTICS,
            SessionState.SESSION_STATE,
            Locks.LOCKS,
            Sessions.SESSIONS,
            Triggers.TRIGGERS,
            Domains.DOMAINS,
            Constants.CONSTANTS,
            FunctionColumns.FUNCTION_COLUMNS,
            Constraints.CONSTRAINTS,
            CrossReferences.CROSS_REFERENCES,
            InDoubt.IN_DOUBT,
            Views.VIEWS,
            Collations.COLLATIONS,
            ColumnPrivileges.COLUMN_PRIVILEGES,
            TablePrivileges.TABLE_PRIVILEGES,
            Schemata.SCHEMATA,
            FunctionAliases.FUNCTION_ALIASES,
            Rights.RIGHTS,
            Roles.ROLES,
            Users.USERS,
            Sequences.SEQUENCES,
            Help.HELP,
            Settings.SETTINGS,
            Catalogs.CATALOGS,
            TypeInfo.TYPE_INFO,
            TableTypes.TABLE_TYPES,
            Indexes.INDEXES,
            Columns.COLUMNS,
            Tables.TABLES);
    }
}
