/**
 * This class is generated by jOOQ
 */
package jooq.public_;


import jooq.DefaultCatalog;
import jooq.public_.tables.AllTimeStats;
import jooq.public_.tables.CurrentUser;
import jooq.public_.tables.DailyStats;
import jooq.public_.tables.Discounts;
import jooq.public_.tables.Employees;
import jooq.public_.tables.Products;
import jooq.public_.tables.Schedule;
import jooq.public_.tables.Users;
import jooq.public_.tables.YearStats;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 854070843;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.PRODUCTS</code>.
     */
    public final Products PRODUCTS = jooq.public_.tables.Products.PRODUCTS;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public final Users USERS = jooq.public_.tables.Users.USERS;

    /**
     * The table <code>PUBLIC.EMPLOYEES</code>.
     */
    public final Employees EMPLOYEES = jooq.public_.tables.Employees.EMPLOYEES;

    /**
     * The table <code>PUBLIC.CURRENT_USER</code>.
     */
    public final CurrentUser CURRENT_USER = jooq.public_.tables.CurrentUser.CURRENT_USER;

    /**
     * The table <code>PUBLIC.DISCOUNTS</code>.
     */
    public final Discounts DISCOUNTS = jooq.public_.tables.Discounts.DISCOUNTS;

    /**
     * The table <code>PUBLIC.SCHEDULE</code>.
     */
    public final Schedule SCHEDULE = jooq.public_.tables.Schedule.SCHEDULE;

    /**
     * The table <code>PUBLIC.DAILY_STATS</code>.
     */
    public final DailyStats DAILY_STATS = jooq.public_.tables.DailyStats.DAILY_STATS;

    /**
     * The table <code>PUBLIC.YEAR_STATS</code>.
     */
    public final YearStats YEAR_STATS = jooq.public_.tables.YearStats.YEAR_STATS;

    /**
     * The table <code>PUBLIC.ALL_TIME_STATS</code>.
     */
    public final AllTimeStats ALL_TIME_STATS = jooq.public_.tables.AllTimeStats.ALL_TIME_STATS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Products.PRODUCTS,
            Users.USERS,
            Employees.EMPLOYEES,
            CurrentUser.CURRENT_USER,
            Discounts.DISCOUNTS,
            Schedule.SCHEDULE,
            DailyStats.DAILY_STATS,
            YearStats.YEAR_STATS,
            AllTimeStats.ALL_TIME_STATS);
    }
}
