/**
 * This class is generated by jOOQ
 */
package jooq.public_;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_3035F31C_4490_4273_8FBC_2D85ECCE6AE2</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_3035F31C_4490_4273_8FBC_2D85ECCE6AE2 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_3035F31C_4490_4273_8FBC_2D85ECCE6AE2", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
