/**
 * This class is generated by jOOQ
 */
package jooq.public_;


import jooq.public_.tables.AllTimeStats;
import jooq.public_.tables.CurrentUser;
import jooq.public_.tables.DailyStats;
import jooq.public_.tables.Discounts;
import jooq.public_.tables.Employees;
import jooq.public_.tables.Products;
import jooq.public_.tables.Schedule;
import jooq.public_.tables.Users;
import jooq.public_.tables.YearStats;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.PRODUCTS</code>.
     */
    public static final Products PRODUCTS = jooq.public_.tables.Products.PRODUCTS;

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public static final Users USERS = jooq.public_.tables.Users.USERS;

    /**
     * The table <code>PUBLIC.EMPLOYEES</code>.
     */
    public static final Employees EMPLOYEES = jooq.public_.tables.Employees.EMPLOYEES;

    /**
     * The table <code>PUBLIC.CURRENT_USER</code>.
     */
    public static final CurrentUser CURRENT_USER = jooq.public_.tables.CurrentUser.CURRENT_USER;

    /**
     * The table <code>PUBLIC.DISCOUNTS</code>.
     */
    public static final Discounts DISCOUNTS = jooq.public_.tables.Discounts.DISCOUNTS;

    /**
     * The table <code>PUBLIC.SCHEDULE</code>.
     */
    public static final Schedule SCHEDULE = jooq.public_.tables.Schedule.SCHEDULE;

    /**
     * The table <code>PUBLIC.DAILY_STATS</code>.
     */
    public static final DailyStats DAILY_STATS = jooq.public_.tables.DailyStats.DAILY_STATS;

    /**
     * The table <code>PUBLIC.YEAR_STATS</code>.
     */
    public static final YearStats YEAR_STATS = jooq.public_.tables.YearStats.YEAR_STATS;

    /**
     * The table <code>PUBLIC.ALL_TIME_STATS</code>.
     */
    public static final AllTimeStats ALL_TIME_STATS = jooq.public_.tables.AllTimeStats.ALL_TIME_STATS;
}
