/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables;


import jooq.public_.Public;
import jooq.public_.tables.records.AllTimeStatsRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllTimeStats extends TableImpl<AllTimeStatsRecord> {

    private static final long serialVersionUID = -1169847672;

    /**
     * The reference instance of <code>PUBLIC.ALL_TIME_STATS</code>
     */
    public static final AllTimeStats ALL_TIME_STATS = new AllTimeStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AllTimeStatsRecord> getRecordType() {
        return AllTimeStatsRecord.class;
    }

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.FOOD_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> FOOD_SOLD = createField("FOOD_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.BAKERY_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> BAKERY_SOLD = createField("BAKERY_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.CANDY_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> CANDY_SOLD = createField("CANDY_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.CHIPS_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> CHIPS_SOLD = createField("CHIPS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.DRINKS_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> DRINKS_SOLD = createField("DRINKS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.SODAS_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> SODAS_SOLD = createField("SODAS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.WATERS_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> WATERS_SOLD = createField("WATERS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.JUICES_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> JUICES_SOLD = createField("JUICES_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.COFFEES_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> COFFEES_SOLD = createField("COFFEES_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.FROZEN_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> FROZEN_SOLD = createField("FROZEN_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.MISC_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> MISC_SOLD = createField("MISC_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.TOTAL_SALES</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> TOTAL_SALES = createField("TOTAL_SALES", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.TOTAL_ITEMS_SOLD</code>.
     */
    public final TableField<AllTimeStatsRecord, Integer> TOTAL_ITEMS_SOLD = createField("TOTAL_ITEMS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.TOTAL_INCOME</code>.
     */
    public final TableField<AllTimeStatsRecord, BigDecimal> TOTAL_INCOME = createField("TOTAL_INCOME", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

    /**
     * The column <code>PUBLIC.ALL_TIME_STATS.TOTAL_PROFIT</code>.
     */
    public final TableField<AllTimeStatsRecord, BigDecimal> TOTAL_PROFIT = createField("TOTAL_PROFIT", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

    /**
     * Create a <code>PUBLIC.ALL_TIME_STATS</code> table reference
     */
    public AllTimeStats() {
        this("ALL_TIME_STATS", null);
    }

    /**
     * Create an aliased <code>PUBLIC.ALL_TIME_STATS</code> table reference
     */
    public AllTimeStats(String alias) {
        this(alias, ALL_TIME_STATS);
    }

    private AllTimeStats(String alias, Table<AllTimeStatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AllTimeStats(String alias, Table<AllTimeStatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllTimeStats as(String alias) {
        return new AllTimeStats(alias, this);
    }

    /**
     * Rename this table
     */
    public AllTimeStats rename(String name) {
        return new AllTimeStats(name, null);
    }
}
