/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables;


import jooq.public_.Public;
import jooq.public_.tables.records.CurrentUserRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrentUser extends TableImpl<CurrentUserRecord> {

    private static final long serialVersionUID = 1372351508;

    /**
     * The reference instance of <code>PUBLIC.CURRENT_USER</code>
     */
    public static final CurrentUser CURRENT_USER = new CurrentUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CurrentUserRecord> getRecordType() {
        return CurrentUserRecord.class;
    }

    /**
     * The column <code>PUBLIC.CURRENT_USER.USER_NAME</code>.
     */
    public final TableField<CurrentUserRecord, String> USER_NAME = createField("USER_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.CURRENT_USER.SALT</code>.
     */
    public final TableField<CurrentUserRecord, byte[]> SALT = createField("SALT", org.jooq.impl.SQLDataType.VARBINARY, this, "");

    /**
     * The column <code>PUBLIC.CURRENT_USER.PASSWORD</code>.
     */
    public final TableField<CurrentUserRecord, byte[]> PASSWORD = createField("PASSWORD", org.jooq.impl.SQLDataType.VARBINARY, this, "");

    /**
     * Create a <code>PUBLIC.CURRENT_USER</code> table reference
     */
    public CurrentUser() {
        this("CURRENT_USER", null);
    }

    /**
     * Create an aliased <code>PUBLIC.CURRENT_USER</code> table reference
     */
    public CurrentUser(String alias) {
        this(alias, CURRENT_USER);
    }

    private CurrentUser(String alias, Table<CurrentUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private CurrentUser(String alias, Table<CurrentUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CurrentUser as(String alias) {
        return new CurrentUser(alias, this);
    }

    /**
     * Rename this table
     */
    public CurrentUser rename(String name) {
        return new CurrentUser(name, null);
    }
}
