/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables;


import jooq.public_.Public;
import jooq.public_.tables.records.DailyStatsRecord;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DailyStats extends TableImpl<DailyStatsRecord> {

    private static final long serialVersionUID = 1571977450;

    /**
     * The reference instance of <code>PUBLIC.DAILY_STATS</code>
     */
    public static final DailyStats DAILY_STATS = new DailyStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DailyStatsRecord> getRecordType() {
        return DailyStatsRecord.class;
    }

    /**
     * The column <code>PUBLIC.DAILY_STATS.DAY</code>.
     */
    public final TableField<DailyStatsRecord, Date> DAY = createField("DAY", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.FOOD_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> FOOD_SOLD = createField("FOOD_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.BAKERY_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> BAKERY_SOLD = createField("BAKERY_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.CANDY_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> CANDY_SOLD = createField("CANDY_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.CHIPS_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> CHIPS_SOLD = createField("CHIPS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.DRINKS_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> DRINKS_SOLD = createField("DRINKS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.SODAS_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> SODAS_SOLD = createField("SODAS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.WATERS_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> WATERS_SOLD = createField("WATERS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.JUICES_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> JUICES_SOLD = createField("JUICES_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.COFFEES_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> COFFEES_SOLD = createField("COFFEES_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.FROZEN_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> FROZEN_SOLD = createField("FROZEN_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.MISC_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> MISC_SOLD = createField("MISC_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.TOTAL_SALES</code>.
     */
    public final TableField<DailyStatsRecord, Integer> TOTAL_SALES = createField("TOTAL_SALES", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.TOTAL_ITEMS_SOLD</code>.
     */
    public final TableField<DailyStatsRecord, Integer> TOTAL_ITEMS_SOLD = createField("TOTAL_ITEMS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.TOTAL_INCOME</code>.
     */
    public final TableField<DailyStatsRecord, BigDecimal> TOTAL_INCOME = createField("TOTAL_INCOME", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

    /**
     * The column <code>PUBLIC.DAILY_STATS.TOTAL_PROFIT</code>.
     */
    public final TableField<DailyStatsRecord, BigDecimal> TOTAL_PROFIT = createField("TOTAL_PROFIT", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

    /**
     * Create a <code>PUBLIC.DAILY_STATS</code> table reference
     */
    public DailyStats() {
        this("DAILY_STATS", null);
    }

    /**
     * Create an aliased <code>PUBLIC.DAILY_STATS</code> table reference
     */
    public DailyStats(String alias) {
        this(alias, DAILY_STATS);
    }

    private DailyStats(String alias, Table<DailyStatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private DailyStats(String alias, Table<DailyStatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DailyStats as(String alias) {
        return new DailyStats(alias, this);
    }

    /**
     * Rename this table
     */
    public DailyStats rename(String name) {
        return new DailyStats(name, null);
    }
}
