/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables;


import jooq.public_.Public;
import jooq.public_.tables.records.DiscountsRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Discounts extends TableImpl<DiscountsRecord> {

    private static final long serialVersionUID = 1689996125;

    /**
     * The reference instance of <code>PUBLIC.DISCOUNTS</code>
     */
    public static final Discounts DISCOUNTS = new Discounts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DiscountsRecord> getRecordType() {
        return DiscountsRecord.class;
    }

    /**
     * The column <code>PUBLIC.DISCOUNTS.PRODUCT</code>.
     */
    public final TableField<DiscountsRecord, String> PRODUCT = createField("PRODUCT", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.OLD_PRICE</code>.
     */
    public final TableField<DiscountsRecord, BigDecimal> OLD_PRICE = createField("OLD_PRICE", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.DISCOUNT_PRICE</code>.
     */
    public final TableField<DiscountsRecord, BigDecimal> DISCOUNT_PRICE = createField("DISCOUNT_PRICE", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.MONDAY</code>.
     */
    public final TableField<DiscountsRecord, Boolean> MONDAY = createField("MONDAY", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.TUESDAY</code>.
     */
    public final TableField<DiscountsRecord, Boolean> TUESDAY = createField("TUESDAY", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.WEDNESDAY</code>.
     */
    public final TableField<DiscountsRecord, Boolean> WEDNESDAY = createField("WEDNESDAY", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.THURSDAY</code>.
     */
    public final TableField<DiscountsRecord, Boolean> THURSDAY = createField("THURSDAY", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.FRIDAY</code>.
     */
    public final TableField<DiscountsRecord, Boolean> FRIDAY = createField("FRIDAY", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>PUBLIC.DISCOUNTS.REPEAT</code>.
     */
    public final TableField<DiscountsRecord, String> REPEAT = createField("REPEAT", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * Create a <code>PUBLIC.DISCOUNTS</code> table reference
     */
    public Discounts() {
        this("DISCOUNTS", null);
    }

    /**
     * Create an aliased <code>PUBLIC.DISCOUNTS</code> table reference
     */
    public Discounts(String alias) {
        this(alias, DISCOUNTS);
    }

    private Discounts(String alias, Table<DiscountsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Discounts(String alias, Table<DiscountsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Discounts as(String alias) {
        return new Discounts(alias, this);
    }

    /**
     * Rename this table
     */
    public Discounts rename(String name) {
        return new Discounts(name, null);
    }
}
