/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables;


import jooq.public_.Public;
import jooq.public_.tables.records.ScheduleRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schedule extends TableImpl<ScheduleRecord> {

    private static final long serialVersionUID = -1782148893;

    /**
     * The reference instance of <code>PUBLIC.SCHEDULE</code>
     */
    public static final Schedule SCHEDULE = new Schedule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScheduleRecord> getRecordType() {
        return ScheduleRecord.class;
    }

    /**
     * The column <code>PUBLIC.SCHEDULE.DAY</code>.
     */
    public final TableField<ScheduleRecord, String> DAY = createField("DAY", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.B1_E1</code>.
     */
    public final TableField<ScheduleRecord, String> B1_E1 = createField("B1_E1", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.B1_E2</code>.
     */
    public final TableField<ScheduleRecord, String> B1_E2 = createField("B1_E2", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.LU_E1</code>.
     */
    public final TableField<ScheduleRecord, String> LU_E1 = createField("LU_E1", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.LU_E2</code>.
     */
    public final TableField<ScheduleRecord, String> LU_E2 = createField("LU_E2", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.B2_E1</code>.
     */
    public final TableField<ScheduleRecord, String> B2_E1 = createField("B2_E1", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.B2_E2</code>.
     */
    public final TableField<ScheduleRecord, String> B2_E2 = createField("B2_E2", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.ST_E1</code>.
     */
    public final TableField<ScheduleRecord, String> ST_E1 = createField("ST_E1", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.ST_E2</code>.
     */
    public final TableField<ScheduleRecord, String> ST_E2 = createField("ST_E2", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.AD_E1</code>.
     */
    public final TableField<ScheduleRecord, String> AD_E1 = createField("AD_E1", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * The column <code>PUBLIC.SCHEDULE.AD_E2</code>.
     */
    public final TableField<ScheduleRecord, String> AD_E2 = createField("AD_E2", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

    /**
     * Create a <code>PUBLIC.SCHEDULE</code> table reference
     */
    public Schedule() {
        this("SCHEDULE", null);
    }

    /**
     * Create an aliased <code>PUBLIC.SCHEDULE</code> table reference
     */
    public Schedule(String alias) {
        this(alias, SCHEDULE);
    }

    private Schedule(String alias, Table<ScheduleRecord> aliased) {
        this(alias, aliased, null);
    }

    private Schedule(String alias, Table<ScheduleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schedule as(String alias) {
        return new Schedule(alias, this);
    }

    /**
     * Rename this table
     */
    public Schedule rename(String name) {
        return new Schedule(name, null);
    }
}
