/**
 * This class is generated by jOOQ
 */
package jooq.public_.tables;


import jooq.public_.Public;
import jooq.public_.tables.records.YearStatsRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class YearStats extends TableImpl<YearStatsRecord> {

    private static final long serialVersionUID = -136985685;

    /**
     * The reference instance of <code>PUBLIC.YEAR_STATS</code>
     */
    public static final YearStats YEAR_STATS = new YearStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<YearStatsRecord> getRecordType() {
        return YearStatsRecord.class;
    }

    /**
     * The column <code>PUBLIC.YEAR_STATS.YEAR</code>.
     */
    public final TableField<YearStatsRecord, Integer> YEAR = createField("YEAR", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.FOOD_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> FOOD_SOLD = createField("FOOD_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.BAKERY_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> BAKERY_SOLD = createField("BAKERY_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.CANDY_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> CANDY_SOLD = createField("CANDY_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.CHIPS_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> CHIPS_SOLD = createField("CHIPS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.DRINKS_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> DRINKS_SOLD = createField("DRINKS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.SODAS_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> SODAS_SOLD = createField("SODAS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.WATERS_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> WATERS_SOLD = createField("WATERS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.JUICES_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> JUICES_SOLD = createField("JUICES_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.COFFEES_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> COFFEES_SOLD = createField("COFFEES_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.FROZEN_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> FROZEN_SOLD = createField("FROZEN_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.MISC_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> MISC_SOLD = createField("MISC_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.TOTAL_SALES</code>.
     */
    public final TableField<YearStatsRecord, Integer> TOTAL_SALES = createField("TOTAL_SALES", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.TOTAL_ITEMS_SOLD</code>.
     */
    public final TableField<YearStatsRecord, Integer> TOTAL_ITEMS_SOLD = createField("TOTAL_ITEMS_SOLD", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.TOTAL_INCOME</code>.
     */
    public final TableField<YearStatsRecord, BigDecimal> TOTAL_INCOME = createField("TOTAL_INCOME", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

    /**
     * The column <code>PUBLIC.YEAR_STATS.TOTAL_PROFIT</code>.
     */
    public final TableField<YearStatsRecord, BigDecimal> TOTAL_PROFIT = createField("TOTAL_PROFIT", org.jooq.impl.SQLDataType.DECIMAL.precision(65535, 32767), this, "");

    /**
     * Create a <code>PUBLIC.YEAR_STATS</code> table reference
     */
    public YearStats() {
        this("YEAR_STATS", null);
    }

    /**
     * Create an aliased <code>PUBLIC.YEAR_STATS</code> table reference
     */
    public YearStats(String alias) {
        this(alias, YEAR_STATS);
    }

    private YearStats(String alias, Table<YearStatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private YearStats(String alias, Table<YearStatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearStats as(String alias) {
        return new YearStats(alias, this);
    }

    /**
     * Rename this table
     */
    public YearStats rename(String name) {
        return new YearStats(name, null);
    }
}
